database/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings


from . import views

urlpatterns = [
    #url(r'^create/POST(?P<slug>[\w~]+)$', views.create),
    #url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<delete_id>[0-9]+$)', views.delete, name='delete'),
    url(r'^images/(?P<slugInput>[\w-]+$)', views.images2, name='images2'),
    url(r'^(?P<update_id>[0-9]+$)', views.update, name='update'),
    url(r'^images/(?P<slugInput>[\w-]+$)', views.images, name='images'),
    url(r'^$', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA, document_root=settings.MEDIA_ROOT)

mywebsite/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views

#from django.views.generic.base import TemplateView,RedirectView

from database.views import predictImage

from .views import index, Login, Logout, Registration

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^database/', include('database.urls', namespace='database')),
    url(r'^predictImage$', predictImage, name='predictImage'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^Registration/', Registration, name='registration'),
    url(r'^Logout$', Logout, name='logout'),
    url(r'^Login$', Login, name='login'),
    url(r'^$', index, name='index'),

    

]
    #url(r'^prediction/$', views.prediction, name = 'prediction'), 
    #url(r'^home$', RedirectView.as_view(url='/'), name='home'),
    #url(r'^$', ParameterView.as_view(template_name = 'index.html')),
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA, document_root=settings.MEDIA_ROOT)

database/models.py
from datetime import datetime
from tkinter.tix import Tree
from unicodedata import name
from django.db import models
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from django.utils import timezone, formats
import pytz
import datetime
import os

    # indonesia_tz = pytz.timezone('Asia/Jakarta')
    # time = timezone.localtime(waktu_update)
    # time.strftime("%d %B %Y %H:%M:%S")
class PostModel(models.Model):
    gambar = models.ImageField(upload_to='', null = True, blank = False)
    waktu = models.DateTimeField(auto_now_add=True)
    waktu_update = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, editable=False)

    def waktu_indonesia(self):
        waktu_indo = timezone.localtime(self.waktu, pytz.timezone('Asia/Jakarta'))
        return waktu_indo.strftime("%d %B %Y %H:%M WIB")
    
    def waktu_update_indonesia(self):
        waktu_update_indo = timezone.localtime(self.waktu_update, pytz.timezone('Asia/Jakarta'))
        return waktu_update_indo.strftime("%d %B %Y %H:%M WIB")
    
    LIST_CATEGORY = (
        ('Pneumonia', 'Pneumonia'),
        ('Tuberculosis', 'Tuberculosis'),
        ('COVID19', 'COVID19'),
        ('Normal', 'Normal'),
    )

    category = models.CharField(
        max_length=100,
        choices=LIST_CATEGORY,blank=False
    )

    def save(self):
        self.slug = slugify(self.gambar)
        super(PostModel, self).save()

    def __str__(self):
        return "{}. {}".format(self.id, self.gambar)

database/forms.py
from tkinter import Widget
from django import forms

from .models import PostModel

#class PostForm(forms.Form):
   #nama = forms.CharField(max_length=255)
   #keterangan = forms.CharField()
   #gambar = forms.ImageField()
   
class PostForm(forms.ModelForm):
   class Meta:
      model = PostModel
      fields = [
         'gambar',
         'category',
      ]

      labels={
         'gambar':'Image :',
         'category':'Category :',
      }

      # widget={
      #    'id_gambar' : forms.FileInput(
      #       attrs={
      #          'class':'form-control'}
      #    ),

      #    'id_category' : forms.Select(
      #       attrs={
      #          'class':'form-select'}
      #    ),
      # }
         
      

database/views.py
from random import choice
from django.shortcuts import redirect, render
from django.views import View
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required, permission_required

import os
from PIL import Image

from keras.models import load_model
from keras_preprocessing import image
import tensorflow as tf
import numpy as np

from mywebsite.forms import MainForm

from .models import PostModel
from .forms import PostForm


model_graph = tf.compat.v1.Graph()
with model_graph.as_default():
    tf_session = tf.compat.v1.Session()
    with tf_session.as_default():
        model = load_model('models/model_hybrid4.h5')

def delete(request, delete_id):
    PostModel.objects.filter(id=delete_id).delete()
    return redirect('database:index')

def update(request, update_id):
    image_update = PostModel.objects.filter(id=update_id).first()
    post_model = PostModel.objects.all()

    data={
        'category'  : image_update.category,
        'gambar'  : image_update.gambar,
    }
    post_form = PostForm(request.POST or None, request.FILES or None, initial=data, instance=image_update)

    if request.method == 'POST':
        if post_form.is_valid():
            post_form.save()

        return redirect('database:index')    

    context = {
        "Judul" : "Database of Lung Disease Detection",
        "Subjudul" : "Database Page",
        'nav': [
            ['/','home'],
            ['/database','database']
        ],
        'Post_Model':post_model,
        'Post_Form':post_form,
    }
    return render(request, 'database/index_user.html', context)

def images2(request, slugInput):
    #query
    post_model = PostModel.objects.get(slug=slugInput)
    print("cekkkkkkkkkkkkkkkkk")
    print(post_model)

    context = {
        "Judul" : "Database of Lung Disease Detection",
        "Subjudul" : "Database Page",
        'nav': [
            ['/','home'],
            ['/database','database']
        ],
        'Post_Model':post_model,
        # 'Post_Form':post_form,
    }
    return render(request, 'database/images2.html', context)

def images(request, slugInput):
    #query
    post_model = PostModel.objects.filter(slug=slugInput).first()
    print("cekkkkkkkkkkkkkkkkk")
    print(post_model)

    context = {
        "Judul" : "Database of Lung Disease Detection",
        "Subjudul" : "Database Page",
        'nav': [
            ['/','home'],
            ['/database','database']
        ],
        'Post_Model':post_model,
        # 'Post_Form':post_form,
    }
    return render(request, 'database/images.html', context)

def predictImage(request):
    if request.method == 'POST':
        main_form = MainForm(request.POST, request.FILES)
        if main_form.is_valid():
            
            simpan=request.FILES['gambar']
            fs=FileSystemStorage()
            Path_Gambar=fs.save(simpan.name,simpan)
            Path_Gambar=fs.url(Path_Gambar)


            testimage = 'database/images/' + Path_Gambar
            img = image.load_img(testimage, target_size=(224,224))
            xray_image = image.img_to_array(img)
            xray_image=xray_image/225
            xray_image=xray_image.reshape(1,224,224,3)
            with model_graph.as_default():
                with tf_session.as_default():
                    prediksi = model.predict(xray_image)

            hasil=int(np.argmax(prediksi,axis=1))
            # probability = max(prediksi.tolist()[0])
            # probability = probability*100

            p = PostModel(category="COVID19", gambar=Path_Gambar)
            q = PostModel(category='Normal', gambar=Path_Gambar)
            r = PostModel(category='Tuberculosis', gambar=Path_Gambar)
            s = PostModel(category='Pneumonia', gambar=Path_Gambar)
            
            if hasil==0:
                hasil=p.category
                p.save()
            elif hasil==1:
                hasil=q.category
                q.save()
            elif hasil==2:
                hasil=r.category
                r.save()
            elif hasil==3:
                hasil=s.category
                s.save()

    template_name=None
    if request.user.is_authenticated():
        template_name= 'index_user.html'
    else:
        template_name= 'index_anonymous.html'

    context = {
            'Top' : 'Lung Disease Website',
            'Judul': 'Lung Disease Detection ',
            'Subjudul' : 'Main Page',
            'Main_Form' : main_form,
            'Path_Gambar':Path_Gambar,
            'Hasil':hasil,
            # 'probability':probability,
            #'Main_model':main_model,
           
            'nav': [
                ['/','home'],
                ['/database','database']
            ],
            
        }
    return render(request, template_name, context)

@login_required(login_url='login')
def index(request):
    #query
    post_model = PostModel.objects.all()

    post_form = PostForm(request.POST, request.FILES)

    template_name=None
    if request.user.is_authenticated():
        template_name= 'database/index_user.html'
    else:
        template_name= 'database/index_anonymous.html'
    
    if request.method == 'POST':
        if post_form.is_valid():
            post_form.save()

        #     simpan = request.FILES['gambar']
        #     fss=FileSystemStorage()
        #     Path_Gambar=fss.save(simpan.name,simpan)
        #     Path_Gambar2=fss.url(Path_Gambar)

        # else:
        #     post_model

        return redirect('database:index')    

    context = {
        "Judul" : "Database of Lung Disease Detection",
        "Subjudul" : "Database Page",
        'nav': [
            ['/','home'],
            ['/database','database']
        ],
        'Post_Model':post_model,
        'Post_Form':post_form,

        
    }
    return render(request, template_name, context)

database/templates/database/images.html
{% extends "base_user.html"%}
{% load static %}

{% block app_css%} 
<link rel="stylesheet" type="text/css" href="{% static "database/css/styles.css" %}">
{% endblock app_css%} 

{% block header%} 
<h1 class="display-4">{{ Judul }}</h1>
<p class="lead ">{{Subjudul}}</p>
{% endblock header%} 

{% block content3%}
<div class="" style="height: auto;">
    <h1 class="text-center">Result of Lung Disease Detection Data</h1>
    <h5>
        <div class="text-center" style="margin-top: 20px;">
            <img src="{{Post_Model.gambar}}" class="rounded" alt="">
        </div>
    </h5>
    <h6>
        <div class="text-center">
            <br>
            <h3>Result : {{Post_Model.category}}</h3>
        </div>
    </h6>
</div>
{% endblock content3%}

database/templates/database/images2.html
{% extends "base_user.html"%}
{% load static %}

{% block app_css%} 
<link rel="stylesheet" type="text/css" href="{% static "database/css/styles.css" %}">
{% endblock app_css%} 

{% block header%} 
<h1 class="display-4">{{ Judul }}</h1>
<p class="lead">Halaman Untuk {{Subjudul}}</p>
{% endblock header%} 

{% block content3%}
<div class="" style="height: auto;">
    <h1 class="text-center">Result of Lung Disease Detection Data</h1>
    <h5>
        <div class="text-center" style="margin-top: 20px;">
            <img src="{{Post_Model.gambar}}" class="rounded" alt="">
        </div>
    </h5>
    <h6>
        <div class="text-center">
            <h3>Result : {{Post_Model.category}}</h3>
        </div>
    </h6>
</div>
{% endblock content3%}

database/templates/database/index.html
{% extends "base.html"%}
{% load static %}

{% block app_css%} 
{% load widget_tweaks%}
<link rel="stylesheet" type="text/css" href="{% static "database/css/styles.css" %}">
{% endblock app_css%} 

{% block header%} 
<h1 class="display-4">{{ Judul }}</h1>
<p class="lead">Halaman Untuk {{Subjudul}}</p>
{% endblock header%} 

{% block content3%}
<div class="" style="height: auto;">
    <h3>Please Upload to Add or Update the Database</h3>
    <h5>
        <div class="input-group">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input-group mb-3">
                    {% render_field Post_Form.gambar.label %}
                    {% render_field Post_Form.gambar class="form-control"%}
                </div >
                <div class="input-group mb-3">
                    {% render_field Post_Form.category.label %}
                    {% render_field Post_Form.category class="form-control"%}
                </div>
                <button class="btn btn-primary" type="submit">Send</button>
            </form>
        </div>
    </h5>
</div>
{% endblock content3%}

{% block content2%}        
<div style="height: auto;">
    <br>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <b>Database X-ray Thorax Images</b>
                    </div>
                    <div class="card-body">
                        <table class = "table" >
                            <thead class = "thead-light">
                                <tr>
                                    <th widht="3%">No.</th>
                                    <th width="37%">Category</th>
                                    <th width="20%">File</th>
                                    <th></th>
                                    <th width="20%">Time</th>
                                    <th width="15%">Update</th>
                                    <th width="15%">Delete</th>
                                 </tr>
                            </thead>
                            <tbody>
                                {% for post in Post_Model %}
                                <tr>
                                    <th scope="row">{{forloop.counter}}</th>
                                    <td>{{post.category}} </td>
                                    <td>{{post.gambar}}</td>
                                    <td><a href="images/{{post.slug}}" class="btn btn-info">Here</a></td>
                                    <td>{{post.waktu}}</td>
                                    <td>
                                        <a class="btn btn-warning" href="{% url 'database:update' post.id %}" role="button">Update</a>
                                    </td>
                                    <td>
                                        <a class="btn btn-danger" href="{% url 'database:delete' post.id %}" role="button">Delete</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>          
                    </div>
                </div>
            </div>
         </div>
    </div>             
</div>
{% endblock content2%}

database/templates/database/index_anonymous.html
{% extends "base_anonymous.html"%}
{% load static %}

{% block app_css%} 
{% load widget_tweaks%}
<link rel="stylesheet" type="text/css" href="{% static "database/css/styles.css" %}">
{% endblock app_css%} 

{% block header%} 
<h1 class="display-4">{{ Judul }}</h1>
<p class="lead">Halaman Untuk {{Subjudul}}</p>
{% endblock header%} 

{% block content3%}
<div class="" style="height: auto;">
    <h3>Please Upload to Add or Update the Database</h3>
    <h5>
        <div class="input-group">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input-group mb-3">
                    {% render_field Post_Form.gambar.label %}
                    {% render_field Post_Form.gambar class="form-control"%}
                </div >
                <div class="input-group mb-3">
                    {% render_field Post_Form.category.label %}
                    {% render_field Post_Form.category class="form-control"%}
                </div>
                <button class="btn btn-primary" type="submit">Send</button>
            </form>
        </div>
    </h5>
</div>
{% endblock content3%}

{% block content2%}        
<div style="height: auto;">
    <br>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <b>Database X-ray Thorax Images</b>
                    </div>
                    <div class="card-body">
                        <table class = "table" >
                            <thead class = "thead-light">
                                <tr>
                                    <th widht="3%">No.</th>
                                    <th width="37%">Category</th>
                                    <th width="20%">File</th>
                                    <th></th>
                                    <th width="20%">Time</th>
                                    <th width="15%">Update</th>
                                    <th width="15%">Delete</th>
                                 </tr>
                            </thead>
                            <tbody>
                                {% for post in Post_Model %}
                                <tr>
                                    <th scope="row">{{forloop.counter}}</th>
                                    <td>{{post.category}} </td>
                                    <td>{{post.gambar}}</td>
                                    <td><a href="images/{{post.slug}}" class="btn btn-info">Here</a></td>
                                    <td>{{post.waktu}}</td>
                                    <td>
                                        <a class="btn btn-warning" href="{% url 'database:update' post.id %}" role="button">Update</a>
                                    </td>
                                    <td>
                                        <a class="btn btn-danger" href="{% url 'database:delete' post.id %}" role="button">Delete</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>          
                    </div>
                </div>
            </div>
         </div>
    </div>             
</div>
{% endblock content2%}

database/templates/database/index_user.html
{% extends "base_user.html"%}
{% load static %}
{% load tz %}

{% block app_css%} 
{% load widget_tweaks%}
<link rel="stylesheet" type="text/css" href="{% static "database/css/styles.css" %}">
{% endblock app_css%} 

{% block header%} 
<h1 class="display-4">{{ Judul }}</h1>
<p class="lead">{{Subjudul}}</p>
{% endblock header%} 

{% block content3%}
<div class="" style="height: auto;">
    <h3>Please Upload to Add or Update the Database</h3>
    <h5>
        <div class="input-group">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input-group mb-2">
                    {% render_field Post_Form.category.label %}
                    {% render_field Post_Form.category class="form-control"%}
                </div>
                <div class="input-group mb-3">

                    {% render_field Post_Form.gambar class="form-control"%}
                </div>
                <button class="btn btn-primary" type="submit">Send</button>
            </form>
        </div>
    </h5>
</div>
{% endblock content3%}

{% block content2%}        
<div style="height: auto;">
    <br>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <b>Database X-ray Thorax Images</b>
                    </div>
                    <div class="card-body">
                        <table class = "table" >
                            <thead class = "thead-light">
                                <tr>
                                    <th widht="3%">No.</th>
                                    <th width="37%">Category</th>
                                    <th width="20%">File</th>
                                    <th></th>
                                    <th width="20%">Time</th>
                                    <th width="15%">Update</th>
                                    <th width="15%">Delete</th>
                                 </tr>
                            </thead>
                            <tbody>
                                {% for post in Post_Model %}
                                <tr>
                                    <th scope="row">{{forloop.counter}}</th>
                                    <td>{{post.category}} </td>
                                    <td>{{post.gambar}}</td>
                                    <td><a href="images/{{post.slug}}" class="btn btn-info">Here</a></td>
                                    <td>
                                    {% if post.waktu_update %}
                                        {{ post.waktu_update_indonesia }}
                                    {% else %}
                                        {{ post.waktu_indonesia }}
                                    {% endif %}
                                    </td>
                                    <td>
                                        <a class="btn btn-warning" href="{% url 'database:update' post.id %}" role="button">Update</a>
                                    </td>
                                    <td>
                                        <a class="btn btn-danger" href="{% url 'database:delete' post.id %}" role="button">Delete</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>          
                    </div>
                </div>
            </div>
         </div>
    </div>             
</div>
{% endblock content2%}